name = "BEnlsip"
uuid = "bee95ccb-06bc-4c9e-be8c-975cfa450c5b"
authors = ["Pierre Borie <pierre.borie98@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
